""".env contract for first-run setup (B2, spec 4).

The ONLY module that knows which keys are required and which the app
bakes as defaults. The baked iRacing app credential lives in the
gitignored core/config/_baked.py (generated by scripts/build_release.py
from the founder .env -- the PUBLIC repo never carries it; release
artifacts do, per the spec 2.3 v1 acceptance).

Values are written double-quoted with backslash escaping so passwords
containing spaces, '#', or quotes survive the python-dotenv parse the
app does at startup.
"""

from __future__ import annotations

import os
from pathlib import Path

_CODE_ROOT = Path(__file__).resolve().parent.parent.parent

REQUIRED: tuple[str, ...] = (
    "ANTHROPIC_API_KEY", "IRACING_USERNAME", "IRACING_PASSWORD",
)

try:  # generated at build time; absent in a public checkout
    from core.config._baked import BAKED_DEFAULTS
except ImportError:
    BAKED_DEFAULTS: dict[str, str] = {}

DEFAULTS: dict[str, str] = {
    "IRACING_CLIENT_ID": "",
    "IRACING_CLIENT_SECRET": "",
    **BAKED_DEFAULTS,
}


def env_file() -> Path:
    """The app's .env -- beside app/ core/ scripts/ in both the dev
    checkout and the installed layout (flat root, plan amendment 1)."""
    return _CODE_ROOT / ".env"


def _quote(value: str) -> str:
    """Wrap value in double quotes with backslash escaping.

    Escapes backslashes first, then double quotes, so that passwords
    containing spaces, '#', or quote characters survive the
    python-dotenv parse done at app startup.
    """
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _unquote(value: str) -> str:
    """Strip surrounding double quotes and unescape backslash sequences."""
    if len(value) >= 2 and value[0] == '"' and value[-1] == '"':
        inner = value[1:-1]
        out: list[str] = []
        i = 0
        while i < len(inner):
            if inner[i] == "\\" and i + 1 < len(inner):
                out.append(inner[i + 1])
                i += 2
            else:
                out.append(inner[i])
                i += 1
        return "".join(out)
    return value


def read_env(path: Path | None = None) -> dict[str, str]:
    """Return KEY=VALUE pairs from a .env file; {} when the file is absent."""
    path = path if path is not None else env_file()
    if not path.exists():
        return {}
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        values[key.strip()] = _unquote(val.strip())
    return values


def is_complete(path: Path | None = None) -> bool:
    """Return True when every REQUIRED key is present and non-empty (spec 4)."""
    values = read_env(path)
    return all(values.get(key) for key in REQUIRED)


def write_env(
    values: dict[str, str],
    path: Path | None = None,
    defaults: dict[str, str] | None = None,
) -> Path:
    """Merge new values over the existing file, fill missing keys from
    defaults (never clobbering an existing override), write, and update
    os.environ so the running app sees the keys immediately.

    Args:
        values: Keys to write/overwrite (e.g. from the Setup page form).
        path: Target .env file; uses env_file() when None.
        defaults: Fallback values for keys not already present; uses
            module-level DEFAULTS when None.  Empty-string defaults are
            skipped -- the public checkout has no baked credentials to
            inject and must not write blank KEY= lines.

    Returns:
        The path written.
    """
    path = path if path is not None else env_file()
    defaults = DEFAULTS if defaults is None else defaults
    merged = read_env(path)
    merged.update({k: v.strip() for k, v in values.items()})
    for key, default in defaults.items():
        if default and not merged.get(key):
            merged[key] = default
    lines = [f"{key}={_quote(val)}" for key, val in merged.items()]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.environ.update(merged)
    return path
