"""Cut a Race Engineer release artifact set (B2, spec 7).

Usage:
    .venv\\Scripts\\python.exe scripts\\build_release.py [--bump patch|minor]

Steps: optional version bump in pyproject.toml -> refresh the gitignored
core/config/_baked.py from the founder .env (the public repo never
carries the iRacing app credential; release artifacts do, spec 2.3) ->
write dist/race-engineer-v<ver>.zip (RELEASE_ENTRIES only) +
dist/SHA256SUMS -> print the tag, paths, and SHA.

The zip is FLAT (entries at the zip root) -- apply_update and the
installer both rely on that layout.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
import zipfile
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from core.update.manifest import RELEASE_ENTRIES  # noqa: E402
from core.update.version import bump_version, get_version  # noqa: E402

_EXCLUDED_DIR_NAMES = {"__pycache__", ".venv"}
_BAKED_PATH = _ROOT / "core" / "config" / "_baked.py"


def write_pyproject_version(pyproject: Path, new_version: str) -> None:
    """Rewrite the [project] version line in place (format-preserving)."""
    text = pyproject.read_text(encoding="utf-8")
    updated, count = re.subn(
        r'^version = "[^"]+"', f'version = "{new_version}"',
        text, count=1, flags=re.MULTILINE,
    )
    if count != 1:
        raise ValueError(f"version line not found in {pyproject}")
    pyproject.write_text(updated, encoding="utf-8")


def refresh_baked_credentials(env_path: Path, out_path: Path) -> bool:
    """Generate core/config/_baked.py from the founder .env.

    Returns False (writing nothing) when the credential is absent -- the
    release then ships without a baked iRacing app cred and the Setup
    page says so.
    """
    from dotenv import dotenv_values

    values = dotenv_values(env_path)
    client_id = values.get("IRACING_CLIENT_ID") or ""
    client_secret = values.get("IRACING_CLIENT_SECRET") or ""
    if not client_id or not client_secret:
        return False
    out_path.write_text(
        '"""GENERATED by scripts/build_release.py - do not commit."""\n'
        "BAKED_DEFAULTS = {\n"
        f"    'IRACING_CLIENT_ID': {client_id!r},\n"
        f"    'IRACING_CLIENT_SECRET': {client_secret!r},\n"
        "}\n",
        encoding="utf-8",
    )
    return True


def _include(rel: Path) -> bool:
    """Return True when this relative path should be included in the zip."""
    if set(rel.parts) & _EXCLUDED_DIR_NAMES:
        return False
    return rel.suffix != ".pyc"


def build_zip(
    code_root: Path, out_zip: Path,
    entries: tuple[str, ...] = RELEASE_ENTRIES,
) -> str:
    """Write the flat release zip; returns its sha256 hex digest."""
    out_zip.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(out_zip, "w", zipfile.ZIP_DEFLATED) as zf:
        for entry in entries:
            src = code_root / entry
            if src.is_file():
                zf.write(src, entry)
                continue
            for path in sorted(src.rglob("*")):
                rel = path.relative_to(code_root)
                if path.is_file() and _include(rel):
                    zf.write(path, rel.as_posix())
    return hashlib.sha256(out_zip.read_bytes()).hexdigest()


def sha256sums_line(sha: str, zip_name: str) -> str:
    """GNU coreutils two-space format -- what check_for_update parses."""
    return f"{sha}  {zip_name}\n"


def main(argv: list[str] | None = None) -> int:
    """Entry point: bump (optional) -> bake credentials -> build zip -> print summary."""
    parser = argparse.ArgumentParser(description="Cut a release artifact set.")
    parser.add_argument("--bump", choices=("patch", "minor"))
    args = parser.parse_args(argv)

    if args.bump:
        new = bump_version(get_version(), args.bump)
        write_pyproject_version(_ROOT / "pyproject.toml", new)
        print(f"Bumped version -> {new}")

    version = get_version()
    if refresh_baked_credentials(_ROOT / ".env", _BAKED_PATH):
        print(f"Refreshed {_BAKED_PATH.name} from .env")
    else:
        print(
            "WARNING: no IRACING_CLIENT_ID/SECRET in .env - "
            "release ships WITHOUT a baked iRacing app credential."
        )

    zip_name = f"race-engineer-v{version}.zip"
    dist = _ROOT / "dist"
    sha = build_zip(_ROOT, dist / zip_name)
    (dist / "SHA256SUMS").write_text(
        sha256sums_line(sha, zip_name), encoding="utf-8"
    )

    print(f"Tag:        v{version}")
    print(f"Zip:        {dist / zip_name}")
    print(f"SHA256SUMS: {dist / 'SHA256SUMS'}")
    print(f"SHA-256:    {sha}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
